export enum UserRole {
  ADMIN = "ADMIN",
  CLIENT = "CLIENT",
  FREELANCER = "FREELANCER",
  AGENCY_OWNER = "AGENCY_OWNER",
  AGENCY_MANAGER = "AGENCY_MANAGER",
  AGENCY_MEMBER = "AGENCY_MEMBER",
  SUPPORT_ADMIN = "SUPPORT_ADMIN",
  FINANCE_ADMIN = "FINANCE_ADMIN",
  MODERATOR = "MODERATOR"
}

export enum AccountStatus {
  ACTIVE = "ACTIVE",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
  DELETED = "DELETED"
}

export enum WorkMode {
  REMOTE = "REMOTE",
  ONSITE = "ONSITE",
  HYBRID = "HYBRID"
}

export enum AvailabilityStatus {
  AVAILABLE = "AVAILABLE",
  LIMITED = "LIMITED",
  UNAVAILABLE = "UNAVAILABLE",
  ON_LEAVE = "ON_LEAVE"
}

export enum VerificationStatus {
  NOT_VERIFIED = "NOT_VERIFIED",
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED"
}

export enum BidStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  SHORTLISTED = "SHORTLISTED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED"
}

export enum ContractStatus {
  PENDING = "PENDING",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  ACTIVE = "ACTIVE",
  IN_PROGRESS = "IN_PROGRESS",
  IN_REVIEW = "IN_REVIEW",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  DISPUTED = "DISPUTED",
  ARCHIVED = "ARCHIVED"
}

export enum ContractPaymentStatus {
  NONE = "NONE",
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED"
}

export enum EscrowStatus {
  NONE = "NONE",
  LOCKED = "LOCKED",
  PARTIAL_RELEASED = "PARTIAL_RELEASED",
  FULLY_RELEASED = "FULLY_RELEASED",
  DISPUTED = "DISPUTED",
  REFUNDED = "REFUNDED"
}

export enum SuspensionLevel {
  WARNING = "WARNING",
  SOFT_SUSPEND = "SOFT_SUSPEND",
  HARD_SUSPEND = "HARD_SUSPEND"
}

export enum AppealStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DENIED = "DENIED",
  PENDING_MORE_INFO = "PENDING_MORE_INFO"
}

export enum DisputeStatus {
  OPEN = "OPEN",
  REVIEWING = "REVIEWING",
  RESOLVED = "RESOLVED",
  APPEALED = "APPEALED"
}

export enum PayoutRequestStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  SENT = "SENT",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED"
}

export enum JobStatus {
  DRAFT = "DRAFT",
  OPEN = "OPEN",
  IN_REVIEW = "IN_REVIEW",
  PAUSED = "PAUSED",
  CLOSED = "CLOSED",
  CANCELLED = "CANCELLED",
  ARCHIVED = "ARCHIVED"
}

export enum JobVisibility {
  PUBLIC = "PUBLIC",
  PRIVATE = "PRIVATE",
  INVITE_ONLY = "INVITE_ONLY"
}

export enum BudgetType {
  FIXED = "FIXED",
  HOURLY = "HOURLY",
  RANGE = "RANGE",
  REQUEST_QUOTE = "REQUEST_QUOTE"
}

export enum SubscriptionStatus {
  TRIALING = "TRIALING",
  ACTIVE = "ACTIVE",
  PAST_DUE = "PAST_DUE",
  CANCELED = "CANCELED",
  EXPIRED = "EXPIRED"
}

export enum BillingCycle {
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY"
}

export enum NotificationType {
  BID_SUBMITTED = "BID_SUBMITTED",
  BID_SHORTLISTED = "BID_SHORTLISTED",
  BID_ACCEPTED = "BID_ACCEPTED",
  CONTRACT_STARTED = "CONTRACT_STARTED",
  NEW_MESSAGE = "NEW_MESSAGE",
  REVIEW_RECEIVED = "REVIEW_RECEIVED",
  VERIFICATION_UPDATED = "VERIFICATION_UPDATED",
  BILLING_UPDATED = "BILLING_UPDATED",
  ADMIN_MODERATION_EVENT = "ADMIN_MODERATION_EVENT",
  ESCROW_PAYMENT_REQUIRED = "ESCROW_PAYMENT_REQUIRED",
  ESCROW_WORK_SUBMITTED = "ESCROW_WORK_SUBMITTED",
  ESCROW_RELEASED = "ESCROW_RELEASED",
  PAYOUT_SENT = "PAYOUT_SENT",
  APPEAL_UPDATED = "APPEAL_UPDATED",
  RECOMMENDATION_DIGEST = "RECOMMENDATION_DIGEST"
}

export enum ReviewTargetType {
  CLIENT = "CLIENT",
  FREELANCER = "FREELANCER"
}

export enum ModerationReportStatus {
  OPEN = "OPEN",
  IN_REVIEW = "IN_REVIEW",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED"
}

export enum ModerationReportPriority {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum ModerationReportSubjectType {
  USER = "USER",
  JOB = "JOB",
  BID = "BID",
  REVIEW = "REVIEW",
  MESSAGE_THREAD = "MESSAGE_THREAD",
  MESSAGE = "MESSAGE"
}

export enum VerificationType {
  IDENTITY = "IDENTITY",
  BUSINESS = "BUSINESS",
  ADDRESS = "ADDRESS",
  CERTIFICATION = "CERTIFICATION",
  PAYMENT_METHOD = "PAYMENT_METHOD"
}

/**
 * Canonical plan caps per tier. Merge with `SubscriptionPlan.entitlements` in the app layer, then pass through
 * `resolvePlanEntitlements` from `@acme/config` for derived fields (`maxActiveContracts`, `canBoostProfile`, …).
 */
export type PlanEntitlements = {
  maxActiveBids: number;
  maxActiveAcceptedContracts: number;
  analyticsTier: "LIMITED" | "ADVANCED" | "AGENCY";
  hasBoost: boolean;
  hasPremiumBadge: boolean;
};
